### ISSUE TITLE
"Arguments to path.resolve must be strings" error

### ISSUE THREAD

**Issue by tomwang1013** [sindresorhus/jshint-stylish#33]
> grunt --version
grunt-cli v0.1.13
grunt v0.4.5

> node --version
v0.12.2

```
module.exports = {
  options: {
    reporter: require('jshint-stylish'),
    force: true
  },
  all: [ 'routes/**/*.js', 'models/**/*.js' ],
  server: [ './keystone.js' ]
}
```

> grunt jshint:server --stack
```
Running "jshint:server" (jshint) task
Warning: Arguments to path.resolve must be strings Use --force to continue.
TypeError: Arguments to path.resolve must be strings
  at Object.posix.resolve (path.js:439:13)
  at Object.exports.selectReporter (/home/wangxiantong/learning/cms/node_modules/grunt-contrib-jshint/tasks/lib/jshint.js:62:31)
  at Object.exports.lint (/home/wangxiantong/learning/cms/node_modules/grunt-contrib-jshint/tasks/lib/jshint.js:184:28)
  at Object.<anonymous> (/home/wangxiantong/learning/cms/node_modules/grunt-contrib-jshint/tasks/jshint.js:47:12)
  at Object.<anonymous> (/home/wangxiantong/learning/cms/node_modules/grunt/lib/grunt/task.js:264:15)
  at Object.thisTask.fn (/home/wangxiantong/learning/cms/node_modules/grunt/lib/grunt/task.js:82:16)
  at Object.<anonymous> (/home/wangxiantong/learning/cms/node_modules/grunt/lib/util/task.js:301:30)
  at Task.runTaskFn (/home/wangxiantong/learning/cms/node_modules/grunt/lib/util/task.js:251:24)
  at Task.<anonymous> (/home/wangxiantong/learning/cms/node_modules/grunt/lib/util/task.js:300:12)
  at Task.start (/home/wangxiantong/learning/cms/node_modules/grunt/lib/util/task.js:309:5)
  at Object.grunt.tasks (/home/wangxiantong/learning/cms/node_modules/grunt/lib/grunt.js:164:8)
  at Object.module.exports [as cli] (/home/wangxiantong/learning/cms/node_modules/grunt/lib/grunt/cli.js:38:9)
  at Object.<anonymous> (/usr/local/lib/node_modules/grunt-cli/bin/grunt:45:20)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Function.Module.runMain (module.js:501:10)
  at startup (node.js:129:16)
  at node.js:814:3
Aborted due to warnings.
```

Running without ```reporter: require('jshint-stylish'),``` worked!

**Comment by tomwang1013** [comment]
upgrading grunt-contrib-jshint fixed it
